package(
    default_visibility = ["//sumparse:internal"],
    default_testonly = 1,
)

cc_library(
    name = "assertions",
    hdrs = ["assertions.h"],
    srcs = ["assertions.cc"],
    deps = [
        "@googletest//:gtest",
        "@com_google_protobuf//:protobuf",
    ],
)
